import type { CurrencyCode } from './currencies';

export type TxType = 'income' | 'expense';
export type Frequency = 'daily' | 'weekly' | 'monthly' | 'yearly';

export type WalletColor = 'emerald' | 'blue' | 'rose' | 'purple' | 'slate' | 'teal' | 'amber' | 'sky';

export interface Wallet {
  id: string;
  name: string;
  currency: CurrencyCode;
  color: WalletColor;
  /** Balance before any recorded transaction. Current balance is always derived. */
  openingBalance: number;
  createdAt: number;
}

export interface Transaction {
  id: string;
  walletId: string;
  type: TxType;
  /** Always positive, in the wallet's currency. */
  amount: number;
  categoryId: string;
  date: number;
  note: string;
  tags: string[];
  /** Receipt image: a path inside the app's data directory, or a data: URL on web. */
  receipt?: string;
  /** Both legs of a transfer share this id. Internal movement: excluded from income/expense stats. */
  transferId?: string;
  /** Money moved into (expense) or out of (income) a savings goal. Internal movement. */
  goalId?: string;
  /** The same movement expressed in the goal's currency. */
  goalAmount?: number;
  /** Set when the transaction was generated by a recurring rule. */
  recurringId?: string;
}

export interface RecurringRule {
  id: string;
  walletId: string;
  type: TxType;
  amount: number;
  categoryId: string;
  note: string;
  tags: string[];
  frequency: Frequency;
  /** First occurrence; later ones are computed from it so monthly dates never drift. */
  startDate: number;
  /** Number of occurrences already materialised as transactions. */
  occurrences: number;
  active: boolean;
}

export interface Budget {
  id: string;
  categoryId: string;
  limit: number;
  currency: CurrencyCode;
}

export interface Goal {
  id: string;
  name: string;
  targetAmount: number;
  currency: CurrencyCode;
  deadline?: string;
  color: WalletColor;
  /** Amount saved before goal-linked transactions existed (migrated v1 data). */
  openingAmount: number;
  createdAt: number;
}

export interface UserProfile {
  name: string;
  baseCurrency: CurrencyCode;
  pinHash?: string;
  pinSalt?: string;
  biometricUnlock?: boolean;
  notificationsEnabled: boolean;
  /** Local hour (0-23) for the daily logging reminder; undefined = off. */
  reminderHour?: number;
  onboardedAt: number;
  lastOpenDate: number;
  pinPromptSeen?: boolean;
}

export interface AppData {
  version: 2;
  user: UserProfile | null;
  wallets: Wallet[];
  transactions: Transaction[];
  budgets: Budget[];
  goals: Goal[];
  recurring: RecurringRule[];
}

export const emptyData = (): AppData => ({
  version: 2,
  user: null,
  wallets: [],
  transactions: [],
  budgets: [],
  goals: [],
  recurring: [],
});

export const newId = (): string =>
  typeof crypto !== 'undefined' && 'randomUUID' in crypto
    ? crypto.randomUUID()
    : Math.random().toString(36).slice(2) + Date.now().toString(36);
